name: Unit Tests
on: [push, pull_request]
jobs:
  unit-tests:
    strategy:
      matrix:
        python-version:
          - 3.8
        platform:
          - ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: jayclassless/setup-poetry-action@v1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          poetry install

      - name: Test
        run: |
          poetry run pytest --verbose --disable-pytest-warnings --mypy --tidypy
